version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo "$CIRCLE_WORKFLOW_ID"

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Hello World!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  print_workflow_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id

  handle_fail_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          command: echo "Hello Error!"
          when: on_fail

workflows:
  hello-world-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_workflow_id
      - handle_fail_error